led.enable(false)
let strip = neopixel.create(DigitalPin.P7, 4, NeoPixelMode.RGB)
mecanumRobotV2.state()
mecanumRobotV2.setLed(LedCount.Left, LedState.ON)
mecanumRobotV2.setLed(LedCount.Right, LedState.ON)
mecanumRobotV2.setServo(90)
basic.forever(function () {
    strip.showColor(neopixel.colors(NeoPixelColors.Red))
    basic.pause(100)
    strip.showColor(neopixel.colors(NeoPixelColors.Orange))
    basic.pause(100)
    strip.showColor(neopixel.colors(NeoPixelColors.Blue))
    basic.pause(100)
    strip.showColor(neopixel.colors(NeoPixelColors.Green))
    basic.pause(100)
})
